# Generated by Django 4.2.10 on 2024-03-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_appuser_otp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='otp_id',
        ),
    ]
