# Generated by Django 4.2.10 on 2024-03-15 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_appuser_otp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
