# Generated by Django 4.2.10 on 2024-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_appuser_otp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='otp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
