# Generated by Django 5.0.1 on 2024-02-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0002_alter_sharer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharer',
            old_name='image',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='sharer',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
