# Generated by Django 4.2.10 on 2024-03-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0071_sharerupload_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
