# Generated by Django 4.2.10 on 2024-03-15 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0072_alter_sharer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
