# Generated by Django 4.2.10 on 2024-03-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0074_remove_comment_username_comment_sharer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sharer',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
