export const GET_ADMIN_USER_REQUEST = 'GET_ADMIN_USER_REQUEST';
export const GET_ADMIN_USER_SUCCESS = 'GET_ADMIN_USER_SUCCESS';
export const GET_ADMIN_USER_FAIL = 'GET_ADMIN_USER_FAIL';


export const CREATE_USER_ADMIN_REQUEST = 'CREATE_USER_ADMIN_REQUEST';
export const CREATE_USER_ADMIN_SUCCESS = 'CREATE_USER_ADMIN_SUCCESS';
export const CREATE_USER_ADMIN_FAIL = 'CREATE_USER_ADMIN_FAIL';

export const UPDATE_USER_ADMIN_REQUEST = 'UPDATE_USER_ADMIN_REQUEST';
export const UPDATE_USER_ADMIN_SUCCESS = 'UPDATE_USER_ADMIN_SUCCESS';
export const UPDATE_USER_ADMIN_FAIL = 'UPDATE_USER_ADMIN_FAIL';

export const DELETE_USER_ADMIN_REQUEST = 'DELETE_USER_ADMIN_REQUEST';
export const DELETE_USER_ADMIN_SUCCESS = 'DELETE_USER_ADMIN_SUCCESS';
export const DELETE_USER_ADMIN_FAIL = 'DELETE_USER_ADMIN_FAIL';

export const GET_SHARER_INCOME_ADMIN_REQUEST = 'GET_SHARER_INCOME_ADMIN_REQUEST';
export const GET_SHARER_INCOME_ADMIN_SUCCESS = 'GET_SHARER_INCOME_ADMIN_SUCCESS';
export const GET_SHARER_INCOME_ADMIN_FAIL = 'GET_SHARER_INCOME_ADMIN_FAIL';

export const INCOME_SENT_ADMIN_REQUEST = 'INCOME_SENT_ADMIN_REQUEST';
export const INCOME_SENT_ADMIN_SUCCESS = 'INCOME_SENT_ADMIN_SUCCESS';
export const INCOME_SENT_ADMIN_FAIL = 'INCOME_SENT_ADMIN_FAIL';

export const PATCH_SHARER_ADMIN_REQUEST = 'PATCH_SHARER_ADMIN_REQUEST';
export const PATCH_SHARER_ADMIN_SUCCESS = 'PATCH_SHARER_ADMIN_SUCCESS';
export const PATCH_SHARER_ADMIN_FAIL = 'PATCH_SHARER_ADMIN_FAIL';

export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAIL = 'SEARCH_USER_FAIL';

export const SEARCH_SHARER_REQUEST = 'SEARCH_SHARER_REQUEST';
export const SEARCH_SHARER_SUCCESS = 'SEARCH_SHARER_SUCCESS';
export const SEARCH_SHARER_FAIL = 'SEARCH_SHARER_FAIL';


export const CONTACTS_ADMIN_REQUEST = 'CONTACTS_ADMIN_REQUEST';
export const CONTACTS_ADMIN_SUCCESS = 'CONTACTS_ADMIN_SUCCESS';
export const CONTACTS_ADMIN_FAIL = 'CONTACTS_ADMIN_FAIL';


export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAIL = 'DELETE_CONTACT_FAIL';
