export const SHARER_FOLLOW_REQUEST = 'SHARER_FOLLOW_REQUEST'
export const SHARER_FOLLOW_SUCCESS = 'SHARER_FOLLOW_SUCCESS'
export const SHARER_FOLLOW_FAIL = 'SHARER_FOLLOW_FAIL'

export const SHARER_UNFOLLOW_REQUEST = 'SHARER_UNFOLLOW_REQUEST'
export const SHARER_UNFOLLOW_SUCCESS = 'SHARER_UNFOLLOW_SUCCESS'
export const SHARER_UNFOLLOW_FAIL = 'SHARER_UNFOLLOW_FAIL'