export const SHARER_FOLLOW_REQUEST = 'SHARER_FOLLOW_REQUEST'
export const SHARER_FOLLOW_SUCCESS = 'SHARER_FOLLOW_SUCCESS'
export const SHARER_FOLLOW_FAIL = 'SHARER_FOLLOW_FAIL'

export const SHARER_UNFOLLOW_REQUEST = 'SHARER_UNFOLLOW_REQUEST'
export const SHARER_UNFOLLOW_SUCCESS = 'SHARER_UNFOLLOW_SUCCESS'
export const SHARER_UNFOLLOW_FAIL = 'SHARER_UNFOLLOW_FAIL'

export const FOLLOWED_SHARER_LIST_REQUEST = 'FOLLOWED_SHARER_LIST_REQUEST'
export const FOLLOWED_SHARER_LIST_SUCCESS = 'FOLLOWED_SHARER_LIST_SUCCESS'
export const FOLLOWED_SHARER_LIST_FAIL = 'FOLLOWED_SHARER_LIST_FAIL'


export const GET_EXPIRATION_REQUEST = 'GET_EXPIRATION_REQUEST';
export const GET_EXPIRATION_SUCCESS = 'GET_EXPIRATION_SUCCESS';
export const GET_EXPIRATION_FAIL = 'GET_EXPIRATION_FAIL';



export const LOGOUT = 'LOGOUT'
export const UPDATE_IS_FOLLOWING = 'UPDATE_IS_FOLLOWING';



