export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_OTP_SENT_REQUEST = 'USER_OTP_SENT_REQUEST'
export const USER_OTP_SENT_SUCCESS = 'USER_OTP_SENT_SUCCESS'
export const USER_OTP_SENT_FAIL = 'USER_OTP_SENT_FAIL'


export const USER_OTP_RESEND_REQUEST = 'USER_OTP_RESEND_REQUEST'
export const USER_OTP_RESEND_SUCCESS = 'USER_OTP_RESEND_SUCCESS'
export const USER_OTP_RESEND_FAIL = 'USER_OTP_RESEND_FAIL'

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST'
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS'
export const USER_VERIFY_FAIL = 'USER_VERIFY_FAIL'

