export const SHARER_LIST_REQUEST = 'SHARER_LIST_REQUEST'
export const SHARER_LIST_SUCCESS = 'SHARER_LIST_SUCCESS'
export const SHARER_LIST_FAIL = 'SHARER_LIST_FAIL'


export const BE_SHARER_REQUEST = 'BE_SHARER_REQUEST'
export const BE_SHARER_SUCCESS = 'BE_SHARER_SUCCESS'
export const BE_SHARER_FAIL = 'BE_SHARER_FAIL'


export const SHARER_POST_REQUEST = 'SHARER_POST_REQUEST'
export const SHARER_POST_SUCCESS = 'SHARER_POST_SUCCESS'
export const SHARER_POST_FAIL = 'SHARER_POST_FAIL'


export const SHARER_POST_LIST_REQUEST = 'SHARER_POST_LIST_REQUEST'
export const SHARER_POST_LIST_SUCCESS = 'SHARER_POST_LIST_SUCCESS'
export const SHARER_POST_LIST_FAIL = 'SHARER_POST_LIST_FAIL'

export const SHARER_PROFILE_REQUEST = 'SHARER_PROFILE_REQUEST'
export const SHARER_PROFILE_SUCCESS = 'SHARER_PROFILE_SUCCESS'
export const SHARER_PROFILE_FAIL = 'SHARER_PROFILE_FAIL'

export const SHARER_DETAIL_REQUEST = 'SHARER_DETAIL_REQUEST'
export const SHARER_DETAIL_SUCCESS = 'SHARER_DETAIL_SUCCESS'
export const SHARER_DETAIL_FAIL = 'SHARER_DETAIL_FAIL'



export const SHARER_LATEST_POST_REQUEST = 'SHARER_LATEST_POST_REQUEST'
export const SHARER_LATEST_POST_SUCCESS = 'SHARER_LATEST_POST_SUCCESS'
export const SHARER_LATEST_POST_FAIL = 'SHARER_LATEST_POST_FAIL'



//PANG CHECK LANG IF IS_SHARER
export const CHECK_SHARER_SUCCESS = 'CHECK_SHARER_SUCCESS'
export const CHECK_SHARER_REQUEST = 'CHECK_SHARER_REQUEST'
export const CHECK_SHARER_FAIL = 'CHECK_SHARER_FAIL'



export const SHARER_UPDATE_PROFILE_REQUEST = 'SHARER_UPDATE_PROFILE_REQUEST';
export const SHARER_UPDATE_PROFILE_SUCCESS = 'SHARER_UPDATE_PROFILE_SUCCESS';
export const SHARER_UPDATE_PROFILE_FAILURE = 'SHARER_UPDATE_PROFILE_FAILURE';


export const SHARER_DELETE_POST_REQUEST = 'SHARER_DELETE_POST_REQUEST';
export const SHARER_DELETE_POST_SUCCESS = 'SHARER_DELETE_POST_SUCCESS';
export const SHARER_DELETE_POST_FAILURE = 'SHARER_DELETE_POST_FAILURE';
export const REMOVE_DELETED_POST = 'REMOVE_DELETED_POST';


export const SHARER_RATINGS_REQUEST = 'POST_SHARER_RATINGS_REQUEST';
export const POST_SHARER_RATINGS_SUCCESS = 'POST_SHARER_RATINGS_SUCCESS';
export const POST_SHARER_RATINGS_FAILURE = 'POST_SHARER_RATINGS_FAILURE';

export const FETCH_SHARER_RATINGS_REQUEST = 'FETCH_SHARER_RATINGS_REQUEST';
export const FETCH_SHARER_RATINGS_SUCCESS = 'FETCH_SHARER_RATINGS_SUCCESS';
export const FETCH_SHARER_RATINGS_FAILURE = 'FETCH_SHARER_RATINGS_FAILURE';


export const DELETE_SHARER_RATINGS_REQUEST = 'DELETE_SHARER_RATINGS_REQUEST';
export const DELETE_SHARER_RATINGS_SUCCESS = 'DELETE_SHARER_RATINGS_SUCCESS';
export const DELETE_SHARER_RATINGS_FAILURE = 'DELETE_SHARER_RATINGS_FAILURE';

export const PATCH_SHARER_RATINGS_REQUEST = 'PATCH_SHARER_RATINGS_REQUEST';
export const PATCH_SHARER_RATINGS_SUCCESS = 'PATCH_SHARER_RATINGS_SUCCESS';
export const PATCH_SHARER_RATINGS_FAILURE = 'PATCH_SHARER_RATINGS_FAILURE';


export const SHARER_EDIT_POST_REQUEST = 'SHARER_EDIT_POST_REQUEST';
export const SHARER_EDIT_POST_SUCCESS = 'SHARER_EDIT_POST_SUCCESS';
export const SHARER_EDIT_POST_FAILURE = 'SHARER_EDIT_POST_FAILURE';


export const SHARER_POST_COUNT_REQUEST = 'SHARER_POST_COUNT_REQUEST';
export const SHARER_POST_COUNT_SUCCESS = 'SHARER_POST_COUNT_SUCCESS';
export const SHARER_POST_COUNT_FAILURE = 'SHARER_POST_COUNT_FAILURE';




export const SHARER_PREVIEW_LIST_REQUEST = 'SHARER_PREVIEW_LIST_REQUEST';
export const SHARER_PREVIEW_LIST_SUCCESS = 'SHARER_PREVIEW_LIST_SUCCESS';
export const SHARER_PREVIEW_LIST_FAILURE = 'SHARER_PREVIEW_LIST_FAILURE';

export const SHARER_PREVIEW_REQUEST = 'SHARER_PREVIEW_REQUEST';
export const SHARER_PREVIEW_SUCCESS = 'SHARER_PREVIEW_SUCCESS';
export const SHARER_PREVIEW_FAILURE = 'SHARER_PREVIEW_FAILURE';



export const TIP_BOX_SEND_REQUEST = 'TIP_BOX_SEND_REQUEST';
export const TIP_BOX_SEND_SUCCESS = 'TIP_BOX_SEND_SUCCESS';
export const TIP_BOX_SEND_FAILURE = 'TIP_BOX_SEND_FAILURE';


export const GET_DASHBOARD_REQUEST = 'GET_DASHBOARD_REQUEST';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE';


export const GET_TOP_DONOR_REQUEST = 'GET_TOP_DONOR_REQUEST';
export const GET_TOP_DONOR_SUCCESS = 'GET_TOP_DONOR_SUCCESS';
export const GET_TOP_DONOR_FAILURE = 'GET_TOP_DONOR_FAILURE';

export const SHARER_LIST_SORT_REQUEST = "SHARER_LIST_SORT_REQUEST";
export const SHARER_LIST_SORT_SUCCESS = "SHARER_LIST_SORT_SUCCESS";
export const SHARER_LIST_SORT_FAIL = "SHARER_LIST_SORT_FAIL";