export const SHARER_LIST_REQUEST = 'SHARER_LIST_REQUEST'
export const SHARER_LIST_SUCCESS = 'SHARER_LIST_SUCCESS'
export const SHARER_LIST_FAIL = 'SHARER_LIST_FAIL'


export const BE_SHARER_REQUEST = 'BE_SHARER_REQUEST'
export const BE_SHARER_SUCCESS = 'BE_SHARER_SUCCESS'
export const BE_SHARER_FAIL = 'BE_SHARER_FAIL'

