export const SHARER_LIST_REQUEST = 'SHARER_LIST_REQUEST'
export const SHARER_LIST_SUCCESS = 'SHARER_LIST_SUCCESS'
export const SHARER_LIST_FAIL = 'SHARER_LIST_FAIL'


export const BE_SHARER_REQUEST = 'BE_SHARER_REQUEST'
export const BE_SHARER_SUCCESS = 'BE_SHARER_SUCCESS'
export const BE_SHARER_FAIL = 'BE_SHARER_FAIL'


export const SHARER_POST_REQUEST = 'SHARER_POST_REQUEST'
export const SHARER_POST_SUCCESS = 'SHARER_POST_SUCCESS'
export const SHARER_POST_FAIL = 'SHARER_POST_FAIL'


export const SHARER_POST_LIST_REQUEST = 'SHARER_POST_LIST_REQUEST'
export const SHARER_POST_LIST_SUCCESS = 'SHARER_POST_LIST_SUCCESS'
export const SHARER_POST_LIST_FAIL = 'SHARER_POST_LIST_FAIL'

export const SHARER_PROFILE_REQUEST = 'SHARER_PROFILE_REQUEST'
export const SHARER_PROFILE_SUCCESS = 'SHARER_PROFILE_SUCCESS'
export const SHARER_PROFILE_FAIL = 'SHARER_PROFILE_FAIL'

export const SHARER_DETAIL_REQUEST = 'SHARER_DETAIL_REQUEST'
export const SHARER_DETAIL_SUCCESS = 'SHARER_DETAIL_SUCCESS'
export const SHARER_DETAIL_FAIL = 'SHARER_DETAIL_FAIL'



export const SHARER_LATEST_POST_REQUEST = 'SHARER_LATEST_POST_REQUEST'
export const SHARER_LATEST_POST_SUCCESS = 'SHARER_LATEST_POST_SUCCESS'
export const SHARER_LATEST_POST_FAIL = 'SHARER_LATEST_POST_FAIL'



//PANG CHECK LANG IF IS_SHARER
export const CHECK_SHARER_SUCCESS = 'CHECK_SHARER_SUCCESS'
export const CHECK_SHARER_REQUEST = 'CHECK_SHARER_REQUEST'
export const CHECK_SHARER_FAIL = 'CHECK_SHARER_FAIL'


