export const TIER1_LIST_REQUEST = 'TIER1_LIST_REQUEST'
export const TIER1_LIST_SUCCESS = 'TIER1_LIST_SUCCESS'
export const TIER1_LIST_FAIL = 'TIER1_LIST_FAIL'


export const TIER2_LIST_REQUEST = 'TIER2_LIST_REQUEST';
export const TIER2_LIST_SUCCESS = 'TIER2_LIST_SUCCESS';
export const TIER2_LIST_FAIL = 'TIER2_LIST_FAIL';


export const TIER3_LIST_REQUEST = 'TIER3_LIST_REQUEST';
export const TIER3_LIST_SUCCESS = 'TIER3_LIST_SUCCESS';
export const TIER3_LIST_FAIL = 'TIER3_LIST_FAIL';