export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"

export const USER_SEND_PASSWORD_REQUEST = 'USER_SEND_PASSWORD_REQUEST'
export const USER_SEND_PASSWORD_SUCCESS = 'USER_SEND_PASSWORD_SUCCESS'
export const USER_SEND_PASSWORD_FAIL = 'USER_SEND_PASSWORD_FAIL'


export const USER_NEW_PASSWORD_REQUEST = 'USER_NEW_PASSWORD_REQUEST'
export const USER_NEW_PASSWORD_SUCCESS = 'USER_NEW_PASSWORD_SUCCESS'
export const USER_NEW_PASSWORD_FAIL = 'USER_NEW_PASSWORD_FAIL'



export const USER_LIKE_REQUEST = 'USER_LIKE_REQUEST'
export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS'
export const USER_LIKE_FAIL = 'USER_LIKE_FAIL'



export const USER_UNLIKE_REQUEST = 'USER_UNLIKE_REQUEST'
export const USER_UNLIKE_SUCCESS = 'USER_UNLIKE_SUCCESS'
export const USER_UNLIKE_FAIL = 'USER_UNLIKE_FAIL'



export const USER_COMMENT_REQUEST = 'USER_COMMENT_REQUEST'
export const USER_COMMENT_SUCCESS = 'USER_COMMENT_SUCCESS'
export const USER_COMMENT_FAIL = 'USER_COMMENT_FAIL'



export const USER_DELETE_COMMENT_REQUEST = 'USER_DELETE_COMMENT_REQUEST'
export const USER_DELETE_COMMENT_SUCCESS = 'USER_DELETE_COMMENT_SUCCESS'
export const USER_DELETE_COMMENT_FAIL = 'USER_DELETE_COMMENT_FAIL'



export const USER_LIST_COMMENT_REQUEST = 'USER_LIST_COMMENT_REQUEST'
export const USER_LIST_COMMENT_SUCCESS = 'USER_LIST_COMMENT_SUCCESS'
export const USER_LIST_COMMENT_FAIL = 'USER_LIST_COMMENT_FAIL'


export const FETCH_LIKES_COUNT_REQUEST = 'FETCH_LIKES_COUNT_REQUEST';
export const FETCH_LIKES_COUNT_SUCCESS = 'FETCH_LIKES_COUNT_SUCCESS';
export const FETCH_LIKES_COUNT_FAILURE = 'FETCH_LIKES_COUNT_FAILURE';