export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS"

export const USER_SEND_PASSWORD_REQUEST = 'USER_SEND_PASSWORD_REQUEST'
export const USER_SEND_PASSWORD_SUCCESS = 'USER_SEND_PASSWORD_SUCCESS'
export const USER_SEND_PASSWORD_FAIL = 'USER_SEND_PASSWORD_FAIL'


export const USER_NEW_PASSWORD_REQUEST = 'USER_NEW_PASSWORD_REQUEST'
export const USER_NEW_PASSWORD_SUCCESS = 'USER_NEW_PASSWORD_SUCCESS'
export const USER_NEW_PASSWORD_FAIL = 'USER_NEW_PASSWORD_FAIL'